[project]
name = "python-exchange-web-services"
version = "0.1.0"
authors = [
    {name = "Piotr OpaÅ‚a", email = "opalapj@gmail.com"},
]
license = {text = "MIT"}
dependencies = ["exchangelib>=5.6.0"]
requires-python = "==3.13.*"

[tool.pdm]
distribution = false
